# Scientific Python
Lecturers = R. Patrick Xian, Santosh Adhikari, Sourin Dey<br>
Date = 07/2022
## 1. math -- built-in math

In [86]:
import math
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']


In [87]:
try:
    del math
except:
    pass
import math as m
from math import sin, pi, radians

In [88]:
sin(pi/2)

1.0

In [89]:
help(radians)

Help on built-in function radians in module math:

radians(x, /)
    Convert angle x from degrees to radians.



In [90]:
sin(radians(30))

0.49999999999999994

In [95]:
m.floor(-1.7), m.ceil(2.5)   # nearest integer down and up

(-2, 3)

In [99]:
m.isnan(m.nan), m.isinf(m.inf)  # check if a number is NaN or infinity


True

In [100]:
m.isnan(-200.4), m.isinf(-200.4)

(False, False)

In [101]:
frac, intg = m.modf(2.519)
print('The integer is {0:0}, the fraction is {1:0.3f}'.format(intg, frac))

The integer is 2.0, the fraction is 0.519


In [104]:
a = [0.1, 0.1, 0.1, 0.3, 0.1, 0.1, 0.1, 0.1, 0.1, 0., 0.1, 0.1]
sum(a), m.fsum(a)

(1.3000000000000003, 1.3)

In [106]:
m.e, m.e == m.exp(1)  # numerical value of e

(2.718281828459045, True)

## 2. numpy -- numeric operations

### 2.1 basic math
Read the list of functions [here](https://numpy.org/doc/stable/reference/index.html#reference)

### 2.2 numpy arrays
#### 2.2.1 array operations

In [107]:
import numpy as np

In [108]:
arr = np.array([-0.1,9.0,300,4])
arr, type(arr)

(array([-1.e-01,  9.e+00,  3.e+02,  4.e+00]), numpy.ndarray)

In [109]:
arr_properties = list(prop for prop in dir(arr) if not prop.startswith('__'))
print(arr_properties)

['T', 'all', 'any', 'argmax', 'argmin', 'argpartition', 'argsort', 'astype', 'base', 'byteswap', 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'ctypes', 'cumprod', 'cumsum', 'data', 'diagonal', 'dot', 'dtype', 'dump', 'dumps', 'fill', 'flags', 'flat', 'flatten', 'getfield', 'imag', 'item', 'itemset', 'itemsize', 'max', 'mean', 'min', 'nbytes', 'ndim', 'newbyteorder', 'nonzero', 'partition', 'prod', 'ptp', 'put', 'ravel', 'real', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 'setfield', 'setflags', 'shape', 'size', 'sort', 'squeeze', 'std', 'strides', 'sum', 'swapaxes', 'take', 'tobytes', 'tofile', 'tolist', 'tostring', 'trace', 'transpose', 'var', 'view']


In [110]:
arr.shape

(4,)

In [111]:
arr2d = np.atleast_2d(arr)
arr2d.shape

(1, 4)

In [112]:
arr2d.squeeze().shape

(4,)

In [113]:
arr2d

array([[-1.e-01,  9.e+00,  3.e+02,  4.e+00]])

In [114]:
arr2d == arr

array([[ True,  True,  True,  True]])

In [115]:
arr.mean()

78.225

In [116]:
intarr = arr.astype('int')
intarr

array([  0,   9, 300,   4])

In [117]:
arr1 = np.array([[1,9,3,12],[0,5,4,2],[19,8,10,7]])
arr1

array([[ 1,  9,  3, 12],
       [ 0,  5,  4,  2],
       [19,  8, 10,  7]])

In [118]:
arr1.shape

(3, 4)

In [119]:
arr1.size

12

In [120]:
arr1.ravel()

array([ 1,  9,  3, 12,  0,  5,  4,  2, 19,  8, 10,  7])

In [121]:
arr1.flatten()

array([ 1,  9,  3, 12,  0,  5,  4,  2, 19,  8, 10,  7])

In [122]:
arr1.sum(), arr1.prod()

(80, 0)

In [123]:
arr1.reshape((2,6))

array([[ 1,  9,  3, 12,  0,  5],
       [ 4,  2, 19,  8, 10,  7]])

In [124]:
arr1

array([[ 1,  9,  3, 12],
       [ 0,  5,  4,  2],
       [19,  8, 10,  7]])

In [125]:
arr1.T

array([[ 1,  0, 19],
       [ 9,  5,  8],
       [ 3,  4, 10],
       [12,  2,  7]])

In [126]:
arr1.swapaxes(0,1)

array([[ 1,  0, 19],
       [ 9,  5,  8],
       [ 3,  4, 10],
       [12,  2,  7]])

In [127]:
np.prod(arr1.T == arr1.swapaxes(0,1))

1

#### 2.2.2 [array indexing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)

In [128]:
arr1

array([[ 1,  9,  3, 12],
       [ 0,  5,  4,  2],
       [19,  8, 10,  7]])

In [129]:
arr1[0,:]

array([ 1,  9,  3, 12])

In [130]:
arr1[0,1]

9

In [131]:
arr1[1:10:2]

array([[0, 5, 4, 2]])

In [132]:
arr1[arr1 > 5]

array([ 9, 12, 19,  8, 10,  7])

In [133]:
# Output the array indices
np.argwhere(arr1 > 5)

array([[0, 1],
       [0, 3],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3]], dtype=int64)

In [134]:
np.where(arr1 > 5)

(array([0, 0, 2, 2, 2, 2], dtype=int64),
 array([1, 3, 0, 1, 2, 3], dtype=int64))

In [135]:
arr1[_]

array([ 9, 12, 19,  8, 10,  7])

#### 2.2.3 [array broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)

In [136]:
arr = np.array([1,2,3,4])

In [137]:
stacked_arr = np.tile(arr, (3,1))
stacked_arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [138]:
np.broadcast_to(arr, (2,arr.size))

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [139]:
stacked_arr + arr

array([[2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8]])

In [140]:
stacked_arr * arr

array([[ 1,  4,  9, 16],
       [ 1,  4,  9, 16],
       [ 1,  4,  9, 16]])

In [141]:
stacked_arr + arr[:-1]

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [142]:
stacked_arr.T

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [143]:
stacked_arr.T + arr[:-1]

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

#### 2.2.4 dimensional operations
Useful for operations on multidimensional arrays

In [144]:
rarr = np.random.rand(14, 3, 2, 8)
rarr.shape

(14, 3, 2, 8)

In [145]:
np.ndim(rarr)

4

In [146]:
np.rollaxis(rarr, 2, start=0).shape

(2, 14, 3, 8)

In [147]:
np.moveaxis(rarr, [0,1,2,3], [1,0,3,2]).shape

(3, 14, 8, 2)

In [148]:
rarr[...,np.newaxis].shape

(14, 3, 2, 8, 1)

In [149]:
np.expand_dims(rarr, axis=2).shape

(14, 3, 1, 2, 8)

In [150]:
np.array([1.3]).item()

1.3

In [151]:
arrsplit = np.split(rarr, 2)
len(arrsplit)

2

In [152]:
arrsplit[0].shape

(7, 3, 2, 8)

In [153]:
arrsplit = np.split(rarr, 2, axis=2)
arrsplit[0].shape

(14, 3, 1, 8)

### 2.3 linear algebra (numpy.linalg)
See the list of functions [here](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html)

In [154]:
from numpy.linalg import norm, multi_dot
import numpy.linalg as nplin

In [155]:
norm([3,4])

5.0

In [156]:
A = np.random.random((10000, 100))
B = np.random.random((100, 1000))
C = np.random.random((1000, 5))
D = np.random.random((5, 333))

In [157]:
%timeit A.dot(B).dot(C).dot(D)

43.8 ms ± 1.92 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [158]:
%timeit multi_dot([A, B, C, D])

8.27 ms ± 157 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [159]:
np.prod(np.isclose(A.dot(B).dot(C).dot(D), multi_dot([A, B, C, D]), atol=1e-8))

1

In [160]:
print(dir(nplin))

['LinAlgError', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_umath_linalg', 'cholesky', 'cond', 'det', 'eig', 'eigh', 'eigvals', 'eigvalsh', 'inv', 'lapack_lite', 'linalg', 'lstsq', 'matrix_power', 'matrix_rank', 'multi_dot', 'norm', 'pinv', 'qr', 'slogdet', 'solve', 'svd', 'tensorinv', 'tensorsolve', 'test']


### 2.4 array iterator (numpy.nditer)
[Documentation](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.nditer.html#numpy.nditer) and [examples](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.nditer.html)

In [161]:
A = (np.arange(12)**2).reshape(3,4)
A

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]], dtype=int32)

In [162]:
it = np.nditer(A, flags=['multi_index'])
for val in it:
    print('index = {}, value = {}'.format(it.multi_index, val))

index = (0, 0), value = 0
index = (0, 1), value = 1
index = (0, 2), value = 4
index = (0, 3), value = 9
index = (1, 0), value = 16
index = (1, 1), value = 25
index = (1, 2), value = 36
index = (1, 3), value = 49
index = (2, 0), value = 64
index = (2, 1), value = 81
index = (2, 2), value = 100
index = (2, 3), value = 121


In [163]:
it = np.nditer(A, flags=['c_index'])
for val in it:
    print('index = {}, value = {}'.format(it.index, val))

index = 0, value = 0
index = 1, value = 1
index = 2, value = 4
index = 3, value = 9
index = 4, value = 16
index = 5, value = 25
index = 6, value = 36
index = 7, value = 49
index = 8, value = 64
index = 9, value = 81
index = 10, value = 100
index = 11, value = 121


numpy.nditer can be slower than nested for loops if the ndarray dimension is equal to or less than 3

### 2.5 nan-avoiding operations and masked array (numpy.ma)

In [164]:
nan_arr = np.array([[-1, 5, 3.], [np.nan, 10, 65536]])
np.max(nan_arr), np.min(nan_arr), np.nanmax(nan_arr), np.nanmin(nan_arr)

(nan, nan, 65536.0, -1.0)

In [165]:
[mth for mth in dir(np) if mth.startswith('nan')]

['nan',
 'nan_to_num',
 'nanargmax',
 'nanargmin',
 'nancumprod',
 'nancumsum',
 'nanmax',
 'nanmean',
 'nanmedian',
 'nanmin',
 'nanpercentile',
 'nanprod',
 'nanquantile',
 'nanstd',
 'nansum',
 'nanvar']

In [166]:
from numpy import ma

In [167]:
marr = ma.masked_invalid(nan_arr)
marr = ma.masked_where(marr > 256, marr)
marr

masked_array(
  data=[[-1.0, 5.0, 3.0],
        [--, 10.0, --]],
  mask=[[False, False, False],
        [ True, False,  True]],
  fill_value=1e+20)

In [168]:
marr.mask

array([[False, False, False],
       [ True, False,  True]])

In [169]:
marr.min()

-1.0

## 3. [scipy](https://docs.scipy.org/doc/scipy/reference/) -- scientific computing

In [170]:
import scipy as sp

In [171]:
from modular import findmodule

ModuleNotFoundError: No module named 'modular'

In [172]:
findmodule(sp)

NameError: name 'findmodule' is not defined

In [173]:
import scipy.constants as const
print(dir(const))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_obsolete_constants', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'grain', 'gram', 'gravitational_con

In [174]:
import scipy.fftpack as fft
print(dir(fft))

['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'basic', 'cc_diff', 'convolve', 'cs_diff', 'dct', 'dctn', 'diff', 'dst', 'dstn', 'fft', 'fft2', 'fftfreq', 'fftn', 'fftshift', 'helper', 'hilbert', 'idct', 'idctn', 'idst', 'idstn', 'ifft', 'ifft2', 'ifftn', 'ifftshift', 'ihilbert', 'irfft', 'itilbert', 'next_fast_len', 'pseudo_diffs', 'realtransforms', 'rfft', 'rfftfreq', 'sc_diff', 'shift', 'ss_diff', 'test', 'tilbert']


In [175]:
import scipy.optimize as opt
print(dir(opt))

['BFGS', 'Bounds', 'HessianUpdateStrategy', 'LbfgsInvHessProduct', 'LinearConstraint', 'NonlinearConstraint', 'OptimizeResult', 'OptimizeWarning', 'RootResults', 'SR1', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__nnls', '__package__', '__path__', '__spec__', '_basinhopping', '_bglu_dense', '_cobyla', '_constraints', '_differentiable_functions', '_differentialevolution', '_dual_annealing', '_group_columns', '_hessian_update_strategy', '_highs', '_lbfgsb', '_linprog', '_linprog_doc', '_linprog_highs', '_linprog_ip', '_linprog_rs', '_linprog_simplex', '_linprog_util', '_lsap', '_lsap_module', '_lsq', '_minimize', '_minpack', '_nnls', '_numdiff', '_qap', '_remove_redundancy', '_root', '_root_scalar', '_shgo', '_shgo_lib', '_slsqp', '_spectral', '_trlib', '_trustregion', '_trustregion_constr', '_trustregion_dogleg', '_trustregion_exact', '_trustregion_krylov', '_trustregion_ncg', '_zeros', 'anderson', 'approx_fprime', 'basinhopping', 'bisect'

#### Test minimization using the [Rosenbrock function](https://en.wikipedia.org/wiki/Rosenbrock_function)

In [176]:
from scipy.optimize import rosen, rosen_der, least_squares, fmin_bfgs

In [177]:
x0 = np.array([1.1, 1.1, 1.1], dtype=np.double)
xopt, fopt, gopt, Bopt, func_calls, grad_calls, warnflag = \
    fmin_bfgs(rosen, x0, fprime=rosen_der, maxiter=2000, full_output=True, retall=False)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 11
         Function evaluations: 17
         Gradient evaluations: 17


In [178]:
res = least_squares(rosen, x0, args=(), method='trf', verbose=1, max_nfev=1e5)

`gtol` termination condition is satisfied.
Function evaluations 5358, initial cost 2.9768e+00, final cost 1.2232e-11, first-order optimality 9.99e-09.


In [179]:
res

 active_mask: array([0., 0., 0.])
        cost: 1.223245301025075e-11
         fun: array([4.94620117e-06])
        grad: array([-1.21177454e-09,  9.98767612e-09,  7.61218441e-09])
         jac: array([[-0.00024499,  0.00201926,  0.001539  ]])
     message: '`gtol` termination condition is satisfied.'
        nfev: 5358
        njev: 5283
  optimality: 9.987676116451502e-09
      status: 1
     success: True
           x: array([1.00099107, 1.00198871, 1.00398906])